[tox]
envlist = py310, py311

[gh-actions]
python =
    3.10: py310
    3.11: py311

[testenv]
setenv =
    PYTHONPATH = {toxinidir}/src
    PIP_NO_CACHE_DIR = 1
deps =
    -e {toxinidir}[test]
commands =
    pytest --cov=src/pyFDN --cov-report=term-missing --cov-report=xml {posargs:tests}

